minimum_pre_commit_version: "3.5.0"
repos:
  # --- Universal sanity checks ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: detect-private-key

  # --- Python formatting + linting ---
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3
        additional_dependencies: []
        files: ^(.*\.py)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(.*\.py)$
      - id: ruff-format
        files: ^(.*\.py)$

  # --- Markdown/JSON/YAML/TOML formatting (via Prettier) ---
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.3.3
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: gradle-spotless-apply
        name: Gradle Spotless (Java/Kotlin) – format
        entry: ./gradlew
        args: [spotlessApply, -q]
        language: system
        pass_filenames: false
        files: \.(java|kt|kts)$